### ISSUE TITLE
make_cdn_cia cannot handle more than 255 content files when building a CIA

### ISSUE THREAD

**Issue by llakssz** [ctrdev/ctrsdk#1]
make_cdn_cia cannot handle more than 255 content files when building a CIA. I think part of the problem is that content_id is only a u8.

**Comment by 173210** [comment]
Check whether the bug is fixed.

**Comment by llakssz** [comment]
I will let you know very soon, 1 hour

**Comment by llakssz** [comment]
Ok, thank you for your work.
Yes, now the content_id can be over 255, thank you!
But, when I try to build the CIA, I receive a 'Floating point exception: 8' error.

I used printf to see what functions are being used.
I can see the program breaks in set_cia_header(), in the for loop: (line 158)

Also, sometimes I receive 'Segmentation fault: 11' when I run the program. I am not sure why.

Thank you for your work, I really appreciate it.

**Comment by 173210** [comment]
Check commit b1885d8285f488944dd7fea4c8869dfca785cb73

**Comment by llakssz** [comment]
Thank you, sometimes I get Bus errors and Segmentation faults. But usually it is ok, and my CIA with 711 content files has built! I will test the program more, and test the CIA, I hope it works.

Thank you again for your work!

**Comment by 173210** [comment]
Ok. BTW, I saw your post on GBATemp.
>haha what!!??
>i opened the issue just... because, just for fun, i didn't think it would get fixed. i wasn't surprised when it was closed and flagged as 'wontfix'...
>
>but he fixed it?!
>crazy, i'll have a look after i eat :)
I tell you the reason.
At first, you said "I think part of the problem is that content_id is only a u8." But it's completely OK. So I flagged wontfix.
But I noticed your guess is wrong when I saw your post on GBATemp because your post has no point. You should learn C more.
By the way, if you don't my rude, can you give me the "reward?" :D

**Comment by llakssz** [comment]
Haha, I should learn more C!... :+1: 
Yes, I was going to send you a message about the reward, I will try to contact you now. Not rude, it is fair.
Thanks again
