### ISSUE TITLE
make_cdn_cia - Receive 'Floating point exception: 8'

### ISSUE THREAD

**Issue by llakssz** [ctrdev/ctrsdk#2]
For a CIA I try to build, on mac I get 'Floating point exception: 8'. On windows, make_cdn_cia.exe just crashes.
I have a core dump from mac, it is nearly 500mb big, I am not sure the best way to share it.
Also, I can share the content that is not building. I do not think it is specific to this content. but it always fails for this content.
Thank you.

**Comment by 173210** [comment]
Use gdb.

**Comment by llakssz** [comment]
I do not know what output you want, I can set up gdb tomorrow.
Right now, I only have lldb, I see this when I run the program with it:

Process 26283 stopped
* thread #1: tid = 0x20a562, 0x00000001000026d7 make_cdn_cia`set_cia_header + 487, queue = 'com.apple.main-thread', stop reason = EXC_ARITHMETIC (code=EXC_I386_DIV, subcode=0x0)
    frame #0: 0x00000001000026d7 make_cdn_cia`set_cia_header + 487
make_cdn_cia`set_cia_header + 487:
-> 0x1000026d7:  divq   %rdi
   0x1000026da:  shlq   $0x1, %rax
   0x1000026de:  movq   -0x2040(%rbp), %rdx
   0x1000026e5:  addq   %rax, %rdx

**Comment by 173210** [comment]
Fixed with commit 3e1bd5ac88a098b037ac126ad433557101bdec0f
Check it out.

**Comment by llakssz** [comment]
No more floating point exception, and I get an cia file! Thank you!
