### ISSUE TITLE
make_cdn_cia: endian.h cause complie error on Xcode 6.0

### ISSUE THREAD

**Issue by 173210** [ctrdev/ctrsdk#4]
endian.h cause complie error on Xcode 6.0.
It tries to call _be64toh.

**Comment by llakssz** [comment]
I think the program compiled when you were included the <endian.h> from the system -(but I had to use portable_endian.h)
But when you added an endian.h file to the project, now it does not compile, even when I change it to portable_endian.h

**Comment by 173210** [comment]
Did you "make clean"?

**Comment by 173210** [comment]
Check out commit 25876a5b69a2c3d091b77b2357a69b17a943be5d.
